# File: .github/workflows/store-artifact.yml
name: Store Artifact

on:
  workflow_dispatch:  # Trigger this workflow manually

jobs:
  build:
    runs-on: windows-latest  # Using Windows runner

    steps:
    - name: Create test directory
      run: mkdir test

    - name: Create data.txt in test directory
      run: echo "This is some sample data." > test/data.txt

    - name: Upload data.txt as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ${{ github.workspace }}/test/data.txt

    - name: List Artifact Contents
      run: dir /S /AD
      shell: cmd

    - name: Download my-artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        run-id: ${{ github.event.workflow_run.id }}
        path: ${{ github.workspace }}/test/data.txt

        
