name: Build

on:
  workflow_dispatch:  # Trigger this workflow manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Create etversion.properties
      run: echo "build.revision.number=100" > F:/build/_work/etversion.properties

    - name: Read and store build.revision.number in zoom_info.txt
      run: |
        REVISION=$(grep 'build.revision.number' F:/build/_work/etversion.properties | cut -d '=' -f2)
        echo "Baseline:$REVISION" > zoom_info.txt

    - name: Upload zoom_info.txt artifact
      uses: actions/upload-artifact@v3
      with:
        name: zoom_info
        path: zoom_info.txt
