name: Build

on:
  workflow_dispatch:  # Trigger this workflow manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Create D:/build/_work directory if it doesn't exist
      run: |
        mkdir "D:\build\_work"
        
    - name: Create etversion.properties
      run: echo "build.revision.number=100" > D:/build/_work/etversion.properties

    - name: Read and store build.revision.number in zoom_info.txt
      run: |
        for /f "tokens=2 delims==" %%A in ('findstr build.revision.number D:\build\_work\etversion.properties') do echo Baseline:%%A > zoom_info.txt

    - name: Upload zoom_info.txt artifact
      uses: actions/upload-artifact@v3
      with:
        name: zoom_info
        path: zoom_info.txt
