name: Build

on:
  workflow_dispatch:  # Trigger this workflow manually for simplicity

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.output_step.outputs.example }}

    steps:
    - name: Generate an output
      id: output_step
      run: echo "::set-output name=example::Hello from the parent workflow!"
