# File: .github/workflows/store-artifact.yml
name: Store Artifact

on:
  workflow_dispatch:  # Trigger this workflow manually

jobs:
  build:
    runs-on: windows-latest  # Using Windows runner

    steps:
    - name: Create data.txt
      run: echo "This is some sample data." > data.txt

    - name: Upload data.txt as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: data.txt  # Uploads only data.txt
