name: Build

# Controls when the action will run. Triggers the workflow on push or pull request events.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:

    # The type of machine to run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
              echo "Simulating Build"
