name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      is_deploy: ${{ steps.set_output.outputs.is_deploy }}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: echo "Simulating Build"

    - name: Save build data
      run: echo "build-data content" > build-data.txt  # Simulate build data

    - name: Set is_deploy output
      id: set_output
      run: echo "is_deploy=true" >> $GITHUB_ENV

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-data
        path: build-data.txt
