name: Build

on:
  workflow_dispatch:  # Trigger this workflow manually

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Create D:/build/_work directory if it doesn't exist
      run: |
        mkdir "D:\build\_work"
        
    - name: Create etversion.properties
      run: echo "build.revision.number=100" > D:/build/_work/etversion.properties

    - name: Read and store build.revision.number in zoom_info.txt (PowerShell)
      run: |
        $content = Get-Content "D:\build\_work\etversion.properties" | Select-String "build.revision.number"
        $revision = $content -replace "build.revision.number=", ""
        "Baseline:$revision" | Out-File -FilePath "zoom_info.txt"
      shell: pwsh

    - name: Upload zoom_info.txt artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./
