# File: .github/workflows/read-artifact.yml
name: Read Artifact

on:
  workflow_run:
    workflows: ["Store Artifact"]  # Trigger after Store Artifact workflow completes
    types:
      - completed

jobs:
  read:
    runs-on: windows-latest  # Using Windows runner

    steps:
    - name: Download my-artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact  # Matches the artifact name from Store Artifact workflow
        path: ./           # Downloads to current directory
        run-id: ${{ github.event.workflow_run.id }}
