name: Notify

on:
  workflow_dispatch:
    # workflows: ["Build"]
    # types:
    #   - completed

jobs:
  notify:
    runs-on: windows-latest

    steps:
    - name: Download zoom_info.txt artifact
      uses: actions/download-artifact@v3
      with:
        name: zoom_info.txt
        path: ./

    - name: Read and display Baseline from zoom_info.txt (PowerShell)
      run: |
        $content = Get-Content "zoom_info.txt"
        if ($content -match "Baseline:(.*)") {
          $baseline = $matches[1]
          echo "Baseline value: $baseline"
        } else {
          echo "No Baseline value found."
        }
      shell: pwsh

    - name: Display Baseline value
      run: echo "The Baseline value is ${{ steps.read-baseline.outputs.BASELINE }}"
