# File: .github/workflows/read-artifact.yml
name: Read Artifact

on:
  workflow_run:
    workflows: ["Store Artifact"]  # Trigger after Store Artifact workflow completes
    types:
      - completed

jobs:
  read:
    runs-on: windows-latest  # Using Windows runner

    steps:
    - name: Download my-artifact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact  # Matches the artifact name from Store Artifact workflow
        path: ./           # Downloads to current directory

    - name: List files in current directory for debugging
      run: dir  # List files in current directory

    - name: Read and display contents of data.txt
      run: type data.txt  # Read and display contents of data.txt
