# File: .github/workflows/read-artifact.yml
name: Read Artifact

permissions: write-all

on:
  workflow_run:
    workflows: ["Store Artifact"]  # Trigger after Store Artifact workflow completes
    types:
      - completed

jobs:
  read:
    runs-on: windows-latest  # Using Windows runner

    steps:
    - name: List Artifact Contents
      run: dir /S /AD
      shell: cmd

    - name: Download my-artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: /test/data.txt
        github-token: ${{ github.token }}
        repository: ${{ github.repository }}
        run-id: ${{ github.event.workflow_run.id }}
