name: Notify

# Controls when the action will run. Triggers the workflow on push or pull request events.
on:
  workflow_run:
    workflows: [Build]
    types:
        - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  notify:

    # The type of machine to run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    - uses: actions/checkout@v4
    - name: Notify
      run: |
             echo "Simulate Notification"
             echo "job URL: ${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.run_id }}/job/${{ github.job }}"
            
