name: Notify

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  use-parent-output:
    runs-on: windows-latest

    steps:
    - name: Run
      run: echo "notify Workflow!"
