name: Notify

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  use-parent-output:
    runs-on: ubuntu-latest

    steps:
    - name: Download the artifact from the parent workflow
      uses: actions/download-artifact@v3
      with:
        name: parent-output
        path: ./artifact

    - name: Read the file content
      run: cat ./artifact/output.txt
