name: Notify

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  use-parent-output:
    runs-on: ubuntu-latest

    steps:
    - name: Use output from parent workflow
      run: |
              echo "Parent workflow output: ${{ github.event.workflow_run.outputs.my_output }}"
